# Example: Maven Build with Template Tests and Notifications
# Place this file in your repository at: .github/workflows/build.yml
# This example shows how to use template tests from a separate repository
# and send notifications via webhook

name: Maven Build and Test with Template

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    uses: your-org/autocode-reusable-workflows/.github/workflows/maven-build-test.yml@main
    with:
      java-version: '21'
      java-distribution: 'temurin'
      artifact-name: 'my-test-results'
      # Use tests from a template repository
      template-repo: 'your-org/java-assignment-template'
      template-tests-path: 'src/test/java'
      template-ref: 'main'
      # Notification webhook URL (can also be passed as secret)
      webhook-url: 'https://your-webhook-service.com/notify'
    secrets:
      # If your template repository is private, provide a token
      TEMPLATE_REPO_TOKEN: ${{ secrets.GH_PAT }}
      # Alternative: pass webhook URL as secret
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

