# Example: Student Assignment Repository
# Place this file in the student repository at: .github/workflows/test.yml
# This workflow runs when a student pushes their code

name: Test Assignment

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test-submission:
    uses: instructor-org/autocode-reusable-workflows/.github/workflows/maven-build-test.yml@main
    with:
      java-version: '17'
      artifact-name: 'assignment-test-results'
      # Pull tests from the instructor's template repository
      template-repo: 'instructor-org/assignment-1-template'
      template-tests-path: 'src/test/java'
      template-ref: 'v1.0'
    secrets:
      # Token to access private template repo with test cases
      TEMPLATE_REPO_TOKEN: ${{ secrets.TEMPLATE_ACCESS_TOKEN }}
      # Webhook to notify grading system
      WEBHOOK_URL: ${{ secrets.GRADING_WEBHOOK }}

